<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title></title>
        <link rel="stylesheet" href="<?php echo $this->url->get('css/bootstrap.min.css')?>">
        <link rel="stylesheet" href="<?php echo $this->url->get('css/simple-sidebar.css')?>">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    </head>
    <body>
        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="<?php echo $this->url->get('js/jquery.min.js')?>"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="<?php echo $this->url->get('js/bootstrap.min.js')?>"></script>
    </body>
</html>
